	<?php View::content() ?>
    <div id='info'>
		<h1>KumbiaPHP está listo para usarse</h1>
        <p><strong>Bienvenido a KumbiaPHP Framework</strong>. El framework ya está listo para desarrollar aplicaciones web con PHP, rápida y fácilmente
       , sin tener que reinventar la rueda, y preocupandose por lo más importante, la lógica de su aplicación.</p>
         <h2>Como empezar</h2>
        <p>En nuestra <a href="http://wiki.kumbiaphp.com/">wiki</a> podrás encontrar información actualizada sobre el uso del framework,
        si estas comenzando con <em>KumbiaPHP</em> deberías realizar  la
        <strong><a href="http://wiki.kumbiaphp.com/Hola_Mundo_KumbiaPHP_Framework">Aplicación Hola Mundo</a></strong>
        tambien puede interesarte saber sobre:</p>
		<ul>
			<li><h3><a href="http://wiki.kumbiaphp.com/Beta2_CRUD_en_KumbiaPHP_Framework">Creacion de CRUD(Create, Read, Update, Delete)</a></h3></li>
			<li><h3><a href="http://wiki.kumbiaphp.com/Como_Usar_los_Modelos_en_KumbiaPHP">Uso de modelos</a></h3></li>
			<li><h3><a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#databases.ini">Configurar conexiones a bases de datos</a></h3></li>
		</ul>
		<p>Estos son solo algunos ejemplos puedes ver más en la <a href="http://wiki.kumbiaphp.com/Categor%C3%ADa:Tutoriales_KumbiaPHP" title="Tutoriales KumbiaPHP">sección de tutoriales de la wiki</a></p>
    </div>
<hr>

		<section class="row">
		
			<div class="four columns">
				<h2>Buttons</h2>
				<div class="row">
					<p class="btn primary"><a href="#">Primary Button</a></p>
				</div>
				<div class="row">
					<p class="btn secondary shrink"><a href="#">Secondary Button</a></p>
				</div>
				<div class="row">
					<p class="btn tertiary"><a href="#">Tertiary Button</a></p>
				</div>
				<div class="row">
					<p class="btn"><a href="#">Generic Button</a></p>
				</div>
				<div class="row">
					<p class="btn oval"><a href="#">Oval Button</a></p>
				</div>
				<div class="row">
					<p class="btn small"><a href="#">Small Button</a></p>
				</div>
				<div class="row">
					<p class="btn medium"><a href="#">Medium Button</a></p>
				</div>
				<div class="row">
					<p class="btn large"><a href="#">Large Button</a></p>
				</div>
			</div>
			<div class="five columns">
				<h2>Forms</h2>
				<form action="" method="" data-form="validate">
					<dl class="field row">
						<dt class="text"><input type="text" placeholder="Text input" required /></dt>
						<dd class="msg"><span class="caret"></span>You filled this out wrong.</dd>
					</dl>
					<dl class="field row">
						<dt class="text"><input type="email" placeholder="Email input" required /></dt>
						<dd class="msg"><span class="caret"></span>You filled this out wrong.</dd>
					</dl>
					<dl class="field row">
						<dt class="text"><input type="password" placeholder="Password" required /></dt>
						<dd class="msg"><span class="caret"></span>Your password is mad weak, yo.</dd>
					</dl>
					<ul class="field row">
						<li class="picker">
							<select>
							  <option SELECTED>Your favorite movie of all time</option>
							  <option>Hitchhiker's Guide To The Galaxy</option>
							  <option>Star Wars Episode 6</option>
							  <option>The Princess Bride</option>
							  <option>Kung Pow</option>
							  <option>Highlander: End Game</option>
							  <option>Street Fighter: The Movie</option>
							</select>
							<a href="#" class="toggle">Your favorite movie of all time<span class="caret"></span></a>
							<ul>
								<li><a href="#">Hitchhiker's Guide To The Galaxy</a></li>
								<li><a href="#">Star Wars</a></li>
								<li><a href="#">The Princess Bride</a></li>
								<li><a href="#">Kung Pow</a></li>
								<li><a href="#">Highlander: End Game</a></li>
								<li><a href="#">Terminator 2</a></li>
								<li><a href="#">Street Fighter: The Movie</a></li>
							</ul>
						</li>
					</ul>
					<dl class="field row">
						<dt class="picker">
							<select>
							  <option SELECTED>MM</option>
							  <option>01</option>
							  <option>02</option>
							  <option>03</option>
							  <option>04</option>
							  <option>05</option>
							  <option>06</option>
							</select>
							<a href="#" class="toggle">MM<span class="caret"></span></a>
							<ul>
								<li><a href="#">Option 1</a></li>
								<li><a href="#">Option 2</a></li>
								<li><a href="#">Option 3</a></li>
								<li><a href="#">Option 4</a></li>
								<li><a href="#">Option 5</a></li>
								<li><a href="#">Option 6</a></li>
							</ul>
						</dt>
						<dt class="picker">
							<select>
							  <option SELECTED>DD</option>
							  <option>01</option>
							  <option>02</option>
							  <option>03</option>
							  <option>04</option>
							  <option>05</option>
							  <option>06</option>
							</select>
							<a href="#" class="toggle">DD<span class="caret"></span></a>
							<ul>
								<li><a href="#">Option 1</a></li>
								<li><a href="#">Option 2</a></li>
								<li><a href="#">Option 3</a></li>
								<li><a href="#">Option 4</a></li>
								<li><a href="#">Option 5</a></li>
								<li><a href="#">Option 6</a></li>
							</ul>
						</dt>
						<dt class="picker">
							<select>
							  <option SELECTED>YYYY</option>
							  <option>1980</option>
							  <option>1981</option>
							  <option>1982</option>
							  <option>1983</option>
							  <option>1984</option>
							  <option>1985</option>
							</select>
							<a href="#" class="toggle">YYYY<span class="caret"></span></a>
							<ul>
								<li><a href="#">1980</a></li>
								<li><a href="#">1981</a></li>
								<li><a href="#">1982</a></li>
								<li><a href="#">1983</a></li>
								<li><a href="#">1984</a></li>
								<li><a href="#">1985</a></li>
							</ul>
						</dt>
						<dd class="msg"><span class="caret"></span>You filled this out wrong.</dd>
						
					</dl>
					<dl class="field row">
						<dt class="textarea"><textarea placeholder="Text Field" required></textarea></dt>
						<dd class="error msg"><span class="caret"></span>You filled this out wrong.</dd>
					</dl>
					<ul class="field row">
						<li>
							<label class="radio" for="radio1">
							  <input name="radio1" type="radio" id="radio1" style="display:none;">
							  <span></span> Radio Button 1
							</label>
						</li>
						<li>
							<label class="radio" for="radio2">
							  <input name="radio1" type="radio" id="radio2" style="display:none;">
							  <span></span> Radio Button 2
							</label>
						</li>
						<li>
							<label class="checkbox" for="checkbox1">
							  <input name="checkbox1" type="checkbox" id="checkbox1" style="display:none;">
							  <span></span> Checkbox 1
							</label>
						</li>
						<li>
							<label class="checkbox checked" for="checkbox2">
							  <input name="checkbox2" type="checkbox" id="checkbox2" style="display:none;">
							  <span></span> Checkbox 2
							</label>
						</li>
					</ul>
					<div class="row">
						<p class="btn submit"><input type="submit" value="Submit"></p>
					</div>
				</form>
			</div>		
			<div class="three columns">
				<h2>Code</h2>
				<pre>h1, h2 {
  font: bold italic 220px georgia, times new roman, serif;
  color: #05390a;
  letter-spacing: -.09em;
  text-shadow: 0 1px 0 #fff;
  -webkit-transition-duration: 1s;
}
						
h2  {
  font-size: 21px;
  text-shadow: 0 1px 0 #fff;
  font-weight: normal;
}
					
.head, .head:hover {
  box-shadow: none;
  margin-top: 30px;
}
				</pre>
			</div>
			
		</section>
		
<hr>
	<section class="row">
			<div class="six columns">
				<h2>Basic Tabs</h2>
				
				<section class="tabs">
					<ul>
						<li><a href="#tab1">Tab 1</a></li>
						<li class="active"><a href="#tab2">Tab 2</a></li>
						<li><a href="#tab3">Tab 3</a></li>
					</ul>
					<div data-tab="tab1">
						<p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante. Etiam aliquet massa et lorem. Mauris dapibus lacus auctor risus. Aenean tempor ullamcorper leo. Vivamus sed magna quis ligula eleifend adipiscing. Duis orci. Aliquam sodales tortor vitae ipsum. Aliquam nulla. Duis aliquam molestie erat. Ut et mauris vel pede varius sollicitudin. Sed ut dolor nec orci tincidunt interdum. Phasellus ipsum. Nunc tristique tempus lectus.</p>
					</div>
					<div class="active" data-tab="tab2">
						<p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc. Duis scelerisque molestie turpis. Sed fringilla, massa eget luctus malesuada, metus eros molestie lectus, ut tempus eros massa ut dolor. Aenean aliquet fringilla sem. Suspendisse sed ligula in ligula suscipit aliquam. Praesent in eros vestibulum mi adipiscing adipiscing. Morbi facilisis. Curabitur ornare consequat nunc. Aenean vel metus. Ut posuere viverra nulla. Aliquam erat volutpat. Pellentesque convallis. Maecenas feugiat, tellus pellentesque pretium posuere, felis lorem euismod felis, eu ornare leo nisi vel felis. Mauris consectetur tortor et purus.</p>
					</div>
					<div data-tab="tab3">
						<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
						<p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio.</p>
					</div>
				</section>
			</div>
			<div class="six columns">
				<h2>Pretty Tabs</h2>
				<section class="pretty tabs">
					<ul>
						<li class="active"><a href="#tab4">Tab 1</a></li>
						<li><a href="#tab5">Tab 2</a></li>
						<li><a href="#tab6">Tab 3</a></li>
						<li><a href="#tab7">Tab 4</a></li>
					</ul>
					<div class="active" data-tab="tab4">
						<p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante. Etiam aliquet massa et lorem. Mauris dapibus lacus auctor risus. Aenean tempor ullamcorper leo. Vivamus sed magna quis ligula eleifend adipiscing. Duis orci. Aliquam sodales tortor vitae ipsum. Aliquam nulla. Duis aliquam molestie erat. Ut et mauris vel pede varius sollicitudin. Sed ut dolor nec orci tincidunt interdum. Phasellus ipsum. Nunc tristique tempus lectus.</p>
					</div>
					<div data-tab="tab5">
						<p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc. Duis scelerisque molestie turpis. Sed fringilla, massa eget luctus malesuada, metus eros molestie lectus, ut tempus eros massa ut dolor. Aenean aliquet fringilla sem. Suspendisse sed ligula in ligula suscipit aliquam. Praesent in eros vestibulum mi adipiscing adipiscing. Morbi facilisis. Curabitur ornare consequat nunc. Aenean vel metus. Ut posuere viverra nulla. Aliquam erat volutpat. Pellentesque convallis. Maecenas feugiat, tellus pellentesque pretium posuere, felis lorem euismod felis, eu ornare leo nisi vel felis. Mauris consectetur tortor et purus.</p>
					</div>
					<div data-tab="tab6">
						<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
						<p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. Nam scelerisque. Donec non libero sed nulla mattis commodo. Ut sagittis. Donec nisi lectus, feugiat porttitor, tempor ac, tempor vitae, pede. Aenean vehicula velit eu tellus interdum rutrum. Maecenas commodo. Pellentesque nec elit. Fusce in lacus. Vivamus a libero vitae lectus hendrerit hendrerit.</p>
					</div>
					<div data-tab="tab7">
						<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
						<p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. Nam scelerisque. Donec non libero sed nulla mattis commodo. Ut sagittis. Donec nisi lectus, feugiat porttitor, tempor ac, tempor vitae, pede. Aenean vehicula velit eu tellus interdum rutrum. Maecenas commodo. Pellentesque nec elit. Fusce in lacus. Vivamus a libero vitae lectus hendrerit hendrerit.</p>
					</div>
				</section>
			</div>
		</section>
			<section class="row">
			<div class="seven columns">
				<h2>Intrinsic Ratio Video Embed</h2>
				<article class="youtube video">
					<iframe width="560" height="315" src="http://www.youtube.com/embed/gye791Yne3E" frameborder="0" allowfullscreen></iframe>
				</article>
			</div>
			<div class="five columns">
				<h2>Vertical Alignment</h2>
				<article class="valign row">
					<div>
						<img src="img/img1.jpg" width="163" />
					</div>
					<div>
						<p>Gumby Framework is cool.</p>
						<p style="margin: 0;">And his Pony pal pokey too!</p>
					</div>
				</article>
				<article class="valign row">
					<div>
						<img src="img/img2.jpg" width="163" />
					</div>
					<div>
						<p>Gumby Framework is cool.</p>
						<p style="margin: 0;">And his Pony pal pokey too!</p>
					</div>
				</article>
			</div>
		</section>
		
		<section class="row" style="padding-top: 30px;">
		  <div class="four columns">
		  	<h2>Skip Links</h2>
		  	<div data-type="skiplink_1">
		  	  <h4>First</h4>
		  	  <p class="skiplink"><a href="#skiplink_2">Skip to second content</a></p>
		  		<p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante.</p>
		  	</div>
		  	<div data-type="skiplink_2">
		  	  <h4>Second</h4>
		  	  <p class="skiplink"><a href="#skiplink_3">Skip to third content</a></p>
		  		<p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc. Duis scelerisque molestie turpis.</p>
		  	</div>
		  	<div data-type="skiplink_3">
		  	  <h4>Third</h4>
		  	  <p class="skiplink"><a href="#skiplink_1">Go back to first content</a></p>
		  		<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante.</p>
		  	</div>
		  </div>
		  <div class="eight columns">
		  	<h2>Skip Nav</h2>
		  	<nav class="skipnav">
		  	  <ul>
  		  	  <li><a href="#skipnav_1">Skip to first content</a></li>
  		  	  <li><a href="#skipnav_2">Skip to second content</a></li>
  		  	  <li><a href="#skipnav_3">Skip to third content</a></li>
		  	  </ul>
		  	</nav>
		  	<div data-type="skipnav_1">
		  	  <h4>First</h4>
		  		<p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. <a href="#skipnav_2" class="skip">Nam elementum</a> quam ullamcorper ante. Etiam aliquet massa et lorem. Mauris dapibus lacus auctor risus. Aenean tempor ullamcorper leo.</p>
		  	</div>
		  	<div data-type="skipnav_2">
		  	  <h4>Second</h4>
		  		<p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra <a href="#skipnav_3" class="skip">massa metus</a> id nunc. Duis scelerisque molestie turpis. Sed fringilla, massa eget luctus malesuada, metus eros molestie lectus, ut tempus eros massa ut dolor.</p>
		  	</div>
		  	<div data-type="skipnav_3">
		  	  <h4>Third</h4>
		  		<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu <a href="#skipnav_1" class="skip">congue orci lorem</a> eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales.</p>
		  	</div>
		  </div>
		</section>
		
    